name: Deploy GKE Cluster

on:
  push:
    branches:
      - main

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
jobs:
  terraform:
    name: 'Terraform Apply'
    runs-on: ubuntu-latest

    steps:
    - name: 'Checkout GitHub Actions'
      uses: actions/checkout@v2

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_CREDENTIALS }}

    - name: 'Setup Terraform'
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.0.0

    - name: 'Terraform Init'
      run: terraform init

    - name: 'Terraform Plan'
      run: terraform plan -var-file="terraform.tfvars"

    - name: 'Terraform Apply'
      run: terraform apply -var-file="terraform.tfvars" -auto-approve

    - name: 'Save Kubeconfig'
      run: echo "${{ steps.terraform.outputs.kubeconfig }}" > $HOME/.kube/config

    - name: 'Upload Kubeconfig'
      uses: actions/upload-artifact@v2
      with:
        name: kubeconfig
        path: $HOME/.kube/config
