name: Deploy GKE Cluster

on:
  push:
    branches:
      - main

jobs:
  terraform:
    name: 'Terraform Apply'
    runs-on: ubuntu-latest

    steps:
    - name: 'Checkout GitHub Actions'
      uses: actions/checkout@v2

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_CREDENTIALS }}

    - name: 'Setup Terraform'
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.0.0

    - name: 'Terraform Init'
      run: terraform init

    - name: 'Terraform Plan'
      run: terraform plan -var-file="terraform.tfvars"

    - name: 'Terraform Apply'
      id: apply
      run: terraform apply -var-file="terraform.tfvars" -auto-approve

    - name: 'Save Kubeconfig Cluster 1'
      run: echo "${{ steps.apply.outputs.kubeconfig_cluster1 }}" > $HOME/.kube/config_cluster1
      shell: bash

    - name: 'Save Kubeconfig Cluster 2'
      run: echo "${{ steps.apply.outputs.kubeconfig_cluster2 }}" > $HOME/.kube/config_cluster2
      shell: bash

    - name: 'Upload Kubeconfig Cluster 1'
      uses: actions/upload-artifact@v2
      with:
        name: kubeconfig_cluster1
        path: $HOME/.kube/config_cluster1

    - name: 'Upload Kubeconfig Cluster 2'
      uses: actions/upload-artifact@v2
      with:
        name: kubeconfig_cluster2
        path: $HOME/.kube/config_cluster2
